import { DefaultTheme } from 'styled-components';
export declare const color: {
    teal50: string;
    teal100: string;
    teal200: string;
    teal300: string;
    teal400: string;
    teal500: string;
    teal600: string;
    teal700: string;
    teal800: string;
    teal900: string;
    blue50: string;
    blue100: string;
    blue200: string;
    blue300: string;
    blue400: string;
    blue500: string;
    blue600: string;
    blue700: string;
    blue800: string;
    blue900: string;
    gray50: string;
    gray100: string;
    gray200: string;
    gray300: string;
    gray400: string;
    gray500: string;
    gray600: string;
    gray700: string;
    gray800: string;
    gray900: string;
    teal: string;
    red: string;
    orange: string;
    amber: string;
    green: string;
    cyan: string;
    blueLight: string;
    blue: string;
    irisBlue: string;
    violet: string;
    magenta: string;
    pink: string;
    brown: string;
    gray: string;
    white: string;
    black: string;
    successLighter: string;
    successLight: string;
    successDefault: string;
    successDark: string;
    errorLighter: string;
    errorLight: string;
    errorDefault: string;
    errorDark: string;
    warningLight: string;
    warningDefault: string;
    warningDark: string;
    warningDarker: string;
    infoLighter: string;
    infoDefault: string;
    infoLight: string;
    infoDark: string;
    infoDarker: string;
};
export declare const transparent = "transparent";
export declare const primary: string;
export declare const successLighter: string;
export declare const successLight: string;
export declare const success: string;
export declare const successDark: string;
export declare const errorLighter: string;
export declare const errorLight: string;
export declare const error: string;
export declare const errorDark: string;
export declare const warningLight: string;
export declare const warning: string;
export declare const warningDark: string;
export declare const warningDarker: string;
export declare const infoLighter: string;
export declare const info: string;
export declare const infoLight: string;
export declare const infoDark: string;
export declare const infoDarker: string;
export declare const fontSizeNumber = 1;
export declare const fontSizeType = "rem";
export declare const fontSize = "1rem";
export declare const fontColor: string;
export declare const fontColorActive: string;
export declare const fontWeightLight = 300;
export declare const fontWeightNormal = 400;
export declare const fontWeightMedium = 500;
export declare const fontWeightSemiBold = 600;
export declare const fontWeightBold = 700;
/**
 * The single definition of the platform type stack — never redeclare it in an app.
 * Montserrat is self-hosted by this package; consumers register the faces with
 * `import '@dexma/ui-components/fonts.css'`. The CJK entries matter: Montserrat has no
 * CJK glyphs, so zh_CN falls through to a proper system face instead of the generic default.
 */
export declare const fontFamily = "\"Montserrat\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", \"PingFang SC\", \"Hiragino Sans GB\", \"Microsoft YaHei\", Helvetica, Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\"";
export declare const pxToRem: (px: number) => number;
export declare const iconSize = "1rem";
export declare const iconColor: string;
export declare const iconColorActive: string;
export declare const backgroundColor: string;
export declare const backgroundColorSelected: string;
export declare const backgroundColorActive: string;
export declare const backgroundColorHover: string;
export declare const backgroundColorFocused: string;
export declare const radius = "4px";
export declare const padding = "20px";
export declare const borderColor: string;
export declare const heightElements = "30px";
export declare const heightComponents: number;
export declare const boxShadow = "0 1px 5px 0 rgba(0,0,0,0.2)";
export declare const boxShadowHover = "0 4px 8px 0 rgba(0, 0, 0, 0.2)";
declare const defaultTheme: DefaultTheme;
export type Theme = DefaultTheme;
export default defaultTheme;
