import { DefaultTheme } from 'styled-components';
export declare const color: {
    teal50: string;
    teal100: string;
    teal200: string;
    teal300: string;
    teal400: string;
    teal500: string;
    teal600: string;
    teal700: string;
    teal800: string;
    teal900: string;
    blue50: string;
    blue100: string;
    blue200: string;
    blue300: string;
    blue400: string;
    blue500: string;
    blue600: string;
    blue700: string;
    blue800: string;
    blue900: string;
    gray50: string;
    gray100: string;
    gray200: string;
    gray300: string;
    gray400: string;
    gray500: string;
    gray600: string;
    gray700: string;
    gray800: string;
    gray900: string;
    teal: string;
    red: string;
    orange: string;
    amber: string;
    green: string;
    cyan: string;
    blueLight: string;
    blue: string;
    irisBlue: string;
    violet: string;
    magenta: string;
    pink: string;
    brown: string;
    gray: string;
    white: string;
    black: string;
};
export declare const transparent = "transparent";
export declare const primary: string;
export declare const success: string;
export declare const warning: string;
export declare const error: string;
export declare const info: string;
export declare const fontSizeNumber = 1;
export declare const fontSizeType = "rem";
export declare const fontSize = "1rem";
export declare const fontColor: string;
export declare const fontColorActive: string;
export declare const fontWeightLight = 300;
export declare const fontWeightNormal = 400;
export declare const fontWeightSemiBold = 600;
export declare const fontWeightBold = 700;
export declare const fontFamily = "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\"";
export declare const pxToRem: (px: number) => number;
export declare const iconSize = "1rem";
export declare const iconColor: string;
export declare const iconColorActive: string;
export declare const backgroundColor: string;
export declare const backgroundColorSelected: string;
export declare const backgroundColorActive: string;
export declare const backgroundColorHover: string;
export declare const backgroundColorFocused: string;
export declare const radius = "4px";
export declare const padding = "20px";
export declare const borderColor: string;
export declare const heightElements = "30px";
export declare const heightComponents: number;
export declare const boxShadow = "0 1px 5px 0 rgba(0,0,0,0.2)";
export declare const boxShadowHover = "0 4px 8px 0 rgba(0, 0, 0, 0.2)";
declare const defaultTheme: DefaultTheme;
export type Theme = DefaultTheme;
export default defaultTheme;
