name: Build and Deploy
on:
    workflow_dispatch:
    push:
        branches:
            - master
        paths:
            - '**/assets/**'
            - '**/stories/**'
            - '**/components/**'
            - '**/styles/**'
            - '**/utils/**'
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v3

            - name: Install dependencies 🔧
              run: npm install

            - name: Build Storybook 🏗️
              run: npm run build-storybook

            - name: Deploy to GitHub Pages 🚀
              uses: crazy-max/ghaction-github-pages@v4
              with:
                  target_branch: gh-pages
                  build_dir: docs
                  commit_message: 'chore(deploy): Storybook'
                  keep_history: false
                  jekyll: false
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
